- name: Check build.gradle.kts
  run: |
    grep -R "debugConfig" 
name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Download Gradle 9.3.1
        run: |
          wget https://services.gradle.org/distributions/gradle-9.3.1-bin.zip
          unzip -q gradle-9.3.1-bin.zip

      - name: Show project files
        run: ls -la

      - name: Build APK
        run: |
          ./gradle-9.3.1/bin/gradle assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
